DROP TABLE IF EXISTS BANK_ACCOUNT;

create table BANK_ACCOUNT
(
    ID        BIGINT not null,
    FULL_NAME VARCHAR(128) not null,
    BALANCE   DOUBLE not null
) ;

alter table BANK_ACCOUNT
    add constraint BANK_ACCOUNT_PK primary key (ID);

Insert into Bank_Account(ID, Full_Name, Balance) values (1, 'Person 1', 1000);
Insert into Bank_Account(ID, Full_Name, Balance) values (2, 'Person 2', 2000);
Insert into Bank_Account(ID, Full_Name, Balance) values (3, 'Person 3', 3000);

commit;

CREATE TABLE DEPARTMENT
(
     "STUDENT_ENROLLED" BIGINT NOT NULL,
     "DEPT_NAME" VARCHAR(255)
);

ALTER TABLE DEPARTMENT ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY("STUDENT_ENROLLED");

CREATE TABLE HOSTEL
(
  "STUDENT_ENROLLED" BIGINT NOT NULL,
  "HOSTEL_NAME" VARCHAR(255)
);

ALTER TABLE HOSTEL ADD CONSTRAINT HOSTEL_PK PRIMARY KEY("STUDENT_ENROLLED");

CREATE TABLE SOCIETY(
  "STUDENT_ENROLLED" BIGINT NOT NULL,
   "SOCIETY" VARCHAR(255)
);

ALTER TABLE SOCIETY ADD CONSTRAINT SOCIETY_PK PRIMARY KEY("STUDENT_ENROLLED");

CREATE TABLE STUDENT(
   "ENROLLMENT_NUM" BIGINT NOT NULL,
    "FIRST_NAME" VARCHAR(255),
    "LAST_NAME" VARCHAR(255),
   "GENDER" VARCHAR(255),
);
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY("ENROLLMENT_NUM");

commit;